#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# normal layout
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.61
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config bottom_padding        50

# mouse configuration
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true


# default settings for applications
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a keepassxc state=floating sticky=on hidden=on
