#!/bin/bash
function flatpak_install () {
	if [ $# -eq 1 ]; then
		flatpak install flathub $1 -y --or-update
	else
		echo "WRONG USAGE OF FUNCTION"
	fi
}

flatpak_install com.nextcloud
flatpak_install us.zoom.Zoom
