#!/bin/bash
[ "$UID" -eq 0 ] || exec sudo "$0" "$@" # Elevate to root

function snap_install () {
	if [ $# -eq 1 ]; then
		snap install $1
	elif [ $# -gt 1 ] && [ $2 == '--classic' ]; then
		snap install $1 --classic
	else
		echo "WRONG USAGE OF COMMAND"
	fi
}

snap_install spotify
