#!/bin/bash
function flatpak_install () {
	if [ $# -eq 1 ]; then
		flatpak install flathub $1 -y --or-update
	fi
}

flatpak_install com.slack.Slack
flatpak_install org.keepassxc.KeePassXC
flatpak_install org.telegram.desktop
